### ISSUE TITLE
Need Immersive Portals for forge 1.20.1

### ISSUE THREAD

**Issue by ErythroCraft** [iPortalTeam/ImmersivePortalsMod#1566]
### Suggestion

Hello

I don't no about this Bug? Maybe you can help to understand?

-------------
I installed Oculus and the mod [Better Recipe Books](https://www.curseforge.com/minecraft/mc-mods/brb)

By using scrolling in recipes book in the Smithing Table this bug was created by launcher.

    SINYTRA CONNECTOR IS PRESENT!
    Please verify issues are not caused by Connector before reporting them to mod authors.
    If you're unsure, file a report on Connector's issue tracker found at https://github.com/Sinytra/Connector/issues.

[crash-2024-06-12_12.47.24-client.txt](https://github.com/user-attachments/files/15803490/crash-2024-06-12_12.47.24-client.txt)
[latest.log - past bin](https://pastebin.com/DdZfGFCg)

**Comment by ParasiticSquid** [comment]
This mod refuses to add actual support for sinytra connector for some ungodly reason so some issues are to be expected if you keep trying to go that route. Even have the comments on curseforge disabled so there no where to actually ask or talk about it except here or in a discord server they have full control of. Take of that what you will.

All in all it's super odd that they keep saying "use the forge version instead" whenever the connector is mentioned yet the forge version is straight up 5 versions behind with no sign of a single update in sight. You would think they would just add proper connector support so forge users can actually use the mod and they can be done with it by this point since it does load but has a couple issues that need fixing. Yet no. Forge players are second class citizens to them so keep that in mind going forward.

**Comment by ErythroCraft** [comment]
@ParasiticSquid I don't know what you mean.
Are you an programmer of this mod?

If the monthly support for this mod is too high, I can also stop the payments.

We are no longer willing to support the iPortalTeam just in the hope of getting an upgrade for the Forge version. 
There are other programmers who do more for less.

**Comment by Nick1st** [comment]
Oh good, ...
Were do I even start

@ErythroCraft 

This is an issue tracker, no complaints forum.

> Need Immersive Portals for forge 1.20.1

This is the wrong repo for that

> Need Immersive Portals for forge 1.20.1

There won't be a Forge version 1.20.1, I only do NeoForge versions after 1.20

> this bug was created 

Yes, and as the message right below that clearly states, if you are using Connector, please open an issue with them instead of us, we can not reasonably fix this.

> Are you an programmer of this mod?

He's not. You can see that by all the nonsense they are writing...

> support for this mod is too high

This. Mod. Is. Complicated.    People. Have. Lives.    Yes. Even. Programmers. Do.

> I can also stop the payments.

If hope you're talking about donations (otherwise you were ripped off). Also, just go ahead. I don't care. Do you know how little money modding makes compared to the immense amount it takes?! Also I hate people trying to blackmail me. 

> We are no longer willing to support the iPortalTeam

Good, I hope I'm never going to have to deal with you, or your stupid issues.  

> There are other programmers who do more for less.

 I don't care, it's your money, do whatever you want with it.



@ParasiticSquid 

Same goes for you, this is an issue tracker, no complaints forum.

> refuses to add actual support for sinytra connector for some ungodly reason

I'm gonna try to explain: THAT. IS. JUST. NOT. HOW. IT. WORKS. There you go.

> Even have the comments on curseforge disabled 

Like most mods, because they can't really be moderated and are a pain to work with, due to there bad implementation (and yes modders also have full control there), making it impossible to deal with such clowns as you.

> they keep saying "use the forge version instead"

Yeah... Right... Use forge 1.19.2 (or a fabic version) if **you want support from US!**

> version is straight up 5 versions behind
Yes. lives... you know? And if I find some time I need to answer jackasses... like you...

>  no sign of a single update in sight

Open your damn eyes. There is a Neo repo. With a nearly functional version for 1.20.5 or so. Stuff takes time. And if you're looking for Forge, that won't happen, as I've probably explained more than a million times now.

> You would think they would just add proper connector support so forge users can actually use the mod and they can be done with it by this point since it does load but has a couple issues that need fixing. Yet no.

Yes. Again. That's not how it works. And even if it would, we do not have enough manpower for it. Perfect support is impossible. This mod does have enough issues on it's own, we don't need connector to make that worse (Su5eD, if you're reading this, keep up the great work :+1: )

> Forge players are second class citizens to them

Yeah, right. Because we do not have the resources to support **your platform of choice**, you have the outrageousness to make such a bold claim? 

But as you seem to have such a deep understanding of this mod, or modding in general /s, how about updating and maintaining the Forge version? We don't have a problem with people doing that. In fact, I'm actively looking for someone interested in doing so. Though I haven't found anyone yet. If you want to actually change something about this either the Forge or the Connector situation, start contributing.
Or shut the fuck up.



And now both of you, please stop filling the issue tracker with such things. Next time use the Discord for that. (And maybe value it more that you get this mod for free!)

**Comment by Nick1st** [comment]
@qouteall moving this to the Forge repo.
